name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  phpstan:
    name: PHPStan analysis
    runs-on: ${{ matrix.image }}

    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        php: ["8.1", "8.2", "8.3"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: pmmp/setup-php-action@2.0.0
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"
          pm-version-major: "5"

      - name: Restore Composer package cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/composer/files
            ~/.cache/composer/vcs
          key: "composer-v2-cache-${{ matrix.php }}-${{ hashFiles('./composer.lock') }}"
          restore-keys: |
            composer-v2-cache-

      - name: Run PHPStan
        run: make phpstan

  codestyle:
    name: Code Style checks
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP and tools
        run: make php/install

      - name: Run PHP-CS-Fixer
        run: make cs/diff

  unittests:
    name: Unit tests
    runs-on: ${{ matrix.image }}

    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu-20.04]
        suittest: ["normal", "with_plugin", "no_test"]
        php: ["8.1", "8.2", "8.3"]
        pmmp: ["5.8.2","5.9.0", "5.10.0"]

    steps:
        - uses: actions/checkout@v4

        - name: Setup PHP and tools
          run: make php/install

        - name: Run PHPUnit
          run: export SUITE_TEST=${{ matrix.suittest }} && export PHP_VERSION=${{ matrix.php }} && export PMMP_TAG=${{ matrix.pmmp }} && make suitetest